-- SQL script to run in Supabase SQL Editor
-- Creates the user_spent table for tracking customer spent amount in PLN

CREATE TABLE IF NOT EXISTS public.user_spent (
    user_id TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, guild_id)
);

-- Enable Row Level Security (RLS) if required
ALTER TABLE public.user_spent ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.user_spent
    FOR SELECT USING (true);

-- Allow write access for everyone (or configure authenticated only)
CREATE POLICY "Allow write access for all" ON public.user_spent
    FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.user_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    price NUMERIC NOT NULL,
    server TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS) if required
ALTER TABLE public.user_purchases ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.user_purchases
    FOR SELECT USING (true);

-- Allow write access for everyone (or configure authenticated only)
CREATE POLICY "Allow write access for all" ON public.user_purchases
    FOR ALL USING (true) WITH CHECK (true);

-- Active discount/reward codes used by the bot
CREATE TABLE IF NOT EXISTS public.active_codes (
    code TEXT PRIMARY KEY,
    user_id TEXT,
    discount NUMERIC NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    reward TEXT,
    reward_amount NUMERIC,
    reward_text TEXT,
    type TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.active_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access active_codes" ON public.active_codes
    FOR SELECT USING (true);

CREATE POLICY "Allow write access active_codes" ON public.active_codes
    FOR ALL USING (true) WITH CHECK (true);
